export const ADD_TODOLIST_REQUEST = "ADD_TODOLIST_REQUEST";
export const ADD_TODOLIST_SUCCESS = "ADD_TODOLIST_SUCCESS";
export const ADD_TODOLIST_FAILURE = "ADD_TODOLIST_FAILURE";

export const INC_LIST_COUNT_REQUEST = "INC_LIST_COUNT_REQUEST";
export const INC_LIST_COUNT_SUCCESS = "INC_LIST_COUNT_SUCCESS ";
export const INC_LIST_COUNT_FAILURE = "INC_LIST_COUNT_FAILURE";

export const CHANGE_LIST_COLOR_REQUEST = "CHANGE_LIST_COLOR_REQUEST";
export const CHANGE_LIST_COLOR_SUCCESS = "CHANGE_LIST_COLOR_SUCCESS ";
export const CHANGE_LIST_COLOR_FAILURE = "CHANGE_LIST_COLOR_FAILURE";

export const REMOVE_LIST_REQUEST = "REMOVE_LIST_REQUEST";
export const REMOVE_LIST_SUCCESS = "REMOVE_LIST_SUCCESS ";
export const REMOVE_LIST_FAILURE = "REMOVE_LIST_FAILURE";

export const HISTORY_BTN_REQUEST = "HISTORY_BTN_REQUEST";
export const HISTORY_BTN_SUCCESS = "HISTORY_BTN_SUCCESS ";
export const HISTORY_BTN_FAILURE = "HISTORY_BTN_FAILURE";

export const RESTORE_LIST_REQUEST = "RESTORE_LIST_REQUEST";
export const RESTORE_LIST_SUCCESS = "RESTORE_LIST_SUCCESS ";
export const RESTORE_LIST_FAILURE = "RESTORE_LIST_FAILURE";

export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS ";
export const DELETE_LIST_FAILURE = "DELETE_LIST_FAILURE";

export const EDIT_LIST_NAME_REQUEST = "EDIT_LIST_NAME_REQUEST";
export const EDIT_LIST_NAME_SUCCESS = "EDIT_LIST_NAME_SUCCESS ";
export const EDIT_LIST_NAME_FAILURE = "EDIT_LIST_NAME_FAILURE";

export const IN_EDIT_LIST = "IN_EDIT_LIST";
export const OUT_EDIT_LIST = "OUT_EDIT_LIST";

const actions = {
  ADD_TODOLIST_REQUEST,
  ADD_TODOLIST_SUCCESS,
  ADD_TODOLIST_FAILURE,
  INC_LIST_COUNT_REQUEST,
  INC_LIST_COUNT_SUCCESS,
  INC_LIST_COUNT_FAILURE,
  CHANGE_LIST_COLOR_REQUEST,
  CHANGE_LIST_COLOR_SUCCESS,
  CHANGE_LIST_COLOR_FAILURE,
  REMOVE_LIST_REQUEST,
  REMOVE_LIST_SUCCESS,
  REMOVE_LIST_FAILURE,
  HISTORY_BTN_REQUEST,
  HISTORY_BTN_SUCCESS,
  HISTORY_BTN_FAILURE,
  RESTORE_LIST_REQUEST,
  RESTORE_LIST_SUCCESS,
  RESTORE_LIST_FAILURE,
  DELETE_LIST_REQUEST,
  DELETE_LIST_SUCCESS,
  DELETE_LIST_FAILURE,
  EDIT_LIST_NAME_REQUEST,
  EDIT_LIST_NAME_SUCCESS,
  EDIT_LIST_NAME_FAILURE,
  IN_EDIT_LIST,
  OUT_EDIT_LIST,
};

export default actions;
