export const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";

export const OUT_EDIT_TODO = "OUT_EDIT_TODO";
export const IN_EDIT_TODO = "IN_EDIT_TODO";

export const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const EDIT_TODO_FAILURE = "EDIT_TODO_FAILURE";

export const TOGGLE_ISCHECKED_REQUEST = "TOGGLE_ISCHECKED_REQUEST";
export const TOGGLE_ISCHECKED_SUCCESS = "TOGGLE_ISCHECKED_SUCCESS";
export const TOGGLE_ISCHECKED_FAILURE = "TOGGLE_ISCHECKED_FAILURE";

export const INC_TODOS_COUNT_REQUEST = "INC_TODOS_COUNT_REQUEST";
export const INC_TODOS_COUNT_SUCCESS = "INC_TODOS_COUNT_SUCCESS ";
export const INC_TODOS_COUNT_FAILURE = "INC_TODOS_COUNT_FAILURE";

export const REMOVE_TODO_REQUEST = "REMOVE_TODO_REQUEST";
export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
export const REMOVE_TODO_FAILURE = "REMOVE_TODO_FAILURE";

export const RESTORE_TODO_REQUEST = "RESTORE_TODO_REQUEST";
export const RESTORE_TODO_SUCCESS = "RESTORE_TODO_SUCCESS";
export const RESTORE_TODO_FAILURE = "RESTORE_TODO_FAILURE";

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE";

const actions = {
  ADD_TODO_REQUEST,
  ADD_TODO_SUCCESS,
  ADD_TODO_FAILURE,
  IN_EDIT_TODO,
  OUT_EDIT_TODO,
  EDIT_TODO_REQUEST,
  EDIT_TODO_SUCCESS,
  EDIT_TODO_FAILURE,
  TOGGLE_ISCHECKED_REQUEST,
  TOGGLE_ISCHECKED_SUCCESS,
  TOGGLE_ISCHECKED_FAILURE,
  INC_TODOS_COUNT_REQUEST,
  INC_TODOS_COUNT_SUCCESS,
  INC_TODOS_COUNT_FAILURE,
  REMOVE_TODO_REQUEST,
  REMOVE_TODO_SUCCESS,
  REMOVE_TODO_FAILURE,
  RESTORE_TODO_REQUEST,
  RESTORE_TODO_SUCCESS,
  RESTORE_TODO_FAILURE,
  DELETE_TODO_REQUEST,
  DELETE_TODO_SUCCESS,
  DELETE_TODO_FAILURE,
};

export default actions;
