export const USER_UPLOAD_IMG_REQUEST = "USER_UPLOAD_IMG_REQUEST";
export const USER_UPLOAD_IMG_SUCCESS = "USER_UPLOAD_IMG_SUCCESS";
export const USER_UPLOAD_IMG_FAILURE = "USER_UPLOAD_IMG_FAILURE";

export const ADD_IMG_REQUEST = "ADD_IMG_REQUEST";
export const ADD_IMG_SUCCESS = "ADD_IMG_SUCCESS";
export const ADD_IMG_FAILURE = "ADD_IMG_FAILURE";

export const IMG_COUNTER_INC_REQUEST = "IMG_COUNTER_INC_REQUEST";
export const IMG_COUNTER_INC_SUCCESS = "IMG_COUNTER_INC_SUCCESS";
export const IMG_COUNTER_INC_FAILURE = "IMG_COUNTER_INC_FAILURE";

export const PROFILE_IMG_REQUEST = "PROFILE_IMG_REQUEST";
export const PROFILE_IMG_SUCCESS = "PROFILE_IMG_SUCCESS";
export const PROFILE_IMG_FAILURE = "PROFILE_IMG_FAILURE";

export const DELETE_IMG_REQUEST = "DELETE_IMG_REQUEST";
export const DELETE_IMG_SUCCESS = "DELETE_IMG_SUCCESS";
export const DELETE_IMG_FAILURE = "DELETE_IMG_FAILURE";

export const IN_IMG_EDIT_MODE = "IN_IMG_EDIT_MODE";
export const OUT_IMG_EDIT_MODE = "OUT_IMG_EDIT_MODE";

const actions = {
  USER_UPLOAD_IMG_REQUEST,
  USER_UPLOAD_IMG_SUCCESS,
  USER_UPLOAD_IMG_FAILURE,
  ADD_IMG_REQUEST,
  ADD_IMG_SUCCESS,
  ADD_IMG_FAILURE,
  IMG_COUNTER_INC_REQUEST,
  IMG_COUNTER_INC_SUCCESS,
  IMG_COUNTER_INC_FAILURE,
  PROFILE_IMG_REQUEST,
  PROFILE_IMG_SUCCESS,
  PROFILE_IMG_FAILURE,
  DELETE_IMG_REQUEST,
  DELETE_IMG_SUCCESS,
  DELETE_IMG_FAILURE,
  IN_IMG_EDIT_MODE,
  OUT_IMG_EDIT_MODE,
};

export default actions;
